version: '3.3'

volumes:
    mysql: {}
    datavolume_drupal: {}

services:
    mysql:
        container_name: db
        build: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "drupal8"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - mysql:/var/lib/mysql
            - ./db_backup:/var/www/db-backup
    web:
        container_name: web
        build: web
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./web/app:/var/www/html
            - datavolume_drupal:/var/www/html
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: "mysql"
            PMA_PORT: 3306
            PMA_USER: "root"
            PMA_PASSWORD: "root"
        restart: always
        depends_on:
          - mysql
        ports:
            - "8080:80"
        volumes:
            - /sessions
